BATCH336A/BATCH336A/Controllers/AuthController.cs
using BATCH336A.DataModel;
using BATCH336A.Models;
using BATCH336A.ViewModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Security.Claims;

namespace BATCH336A.Controllers
{
    public class AuthController : Controller
    {
        private readonly UserModel? userModel;
        private readonly BiodataModel biodataModel;
        private readonly RoleModel roleModel;
        private VMResponse? response = new VMResponse();
        public AuthController(IConfiguration _config)
        {
            userModel = new UserModel(_config);
            biodataModel = new BiodataModel(_config);
            roleModel = new RoleModel(_config);
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public VMResponse Login(VMMUser data)
        {
            VMResponse? response = userModel!.GetByEmail(data.Email!);

            if (response != null)
            {
                if (response.statusCode == System.Net.HttpStatusCode.OK)
                {
                    VMMRole? role = new VMMRole();
                    VMMUser? user = JsonConvert.DeserializeObject<VMMUser>(JsonConvert.SerializeObject(response.data));
                    VMMBiodatum? biodata = biodataModel.GetById((int)user!.BiodataId!);
                    if (data.RoleId != null)
                    {
                        role = roleModel.GetById((int)user.RoleId!);
                    }
                    else
                    {
                        role.Name = "";
                        user.RoleId = 0;
                    }

                    if (user.IsLocked == null || user.IsLocked == false)
                    {
                        if (data.Password == user!.Password)
                        {
                            HttpContext.Session.SetInt32("userId", (int)user.Id!);
                            HttpContext.Session.SetString("userFullname", biodata.Fullname);
                            HttpContext.Session.SetString("userEmail", user.Email!);
                            HttpContext.Session.SetInt32("userBiodataId", (int)user.BiodataId!);
                            HttpContext.Session.SetInt32("userRoleId", (int)user.RoleId);
                            HttpContext.Session.SetString("userRoleName", role.Name!);

                            var claims = new List<Claim>
                            {
                                new Claim(ClaimTypes.Role, user.RoleId.ToString()!),
                            };
                            var identity = new ClaimsIdentity(claims, "CookieAuth");
                            var principal = new ClaimsPrincipal(identity);
                            HttpContext.SignInAsync("CookieAuth", principal);
                            HttpContext.Session.SetString("successMsg", $"Hallo, {HttpContext.Session.GetString("custFullname")}");
                            user.LoginAttempt = 0;
                            user.LastLogin = DateTime.Now;
                            userModel.Update(user);

                        }
                        else
                        {
                            response.statusCode = System.Net.HttpStatusCode.NoContent;

                            if (user.LoginAttempt == null)
                            {
                                user.LoginAttempt = 1;
                                userModel.Update(user);
                            }
                            else
                            {
                                user.LoginAttempt++;
                                userModel.Update(user);
                            }

                            if (user.LoginAttempt >= 5)
                            {
                                user.IsLocked = true;
                                userModel.Update(user);
                            }
                        }
                    }
                    else
                    {
                        response.statusCode = System.Net.HttpStatusCode.Forbidden;
                    }
                }
                else
                {
                    response.statusCode = System.Net.HttpStatusCode.NotFound;
                }
            }

            return response;
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            HttpContext.SignOutAsync("CookieAuth");

            return RedirectToAction("Index", "Home");
        }
    }
}

BATCH336A/BATCH336A/Views/Shared/Partial/_Alert.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    //Get Alert Message from session
    ViewBag.InfoMsg = Context.Session.GetString("infoMsg") ?? "";
    ViewBag.WarnMsg = Context.Session.GetString("warnMsg") ?? "";
    ViewBag.ErrMsg = Context.Session.GetString("errMsg") ?? "";

    //Reset Alert Message from Session
    Context.Session.SetString("infoMsg", string.Empty);
    Context.Session.SetString("warnMsg", string.Empty);
    Context.Session.SetString("errMsg", string.Empty);

}
<div id="alertPlaceholder"></div>


<script>
    function alert(message, bscolor) {
        $("#alertPlaceholder").append(`<div class="alert alert-${bscolor} alert-dismissible fade show mt-1" role="alert">
                                                        <i class="fas fa-circle-info text-${bscolor}"></i>
                                                        <span> ${message}</span>
                                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                </div>`);
    };
    function alert(message, bscolor, id) {
        $(`${id} .alert`).remove();
        $(`${id}`).append(`<div class="alert alert-${bscolor} alert-dismissible fade show mt-1" id="alertAuth" role="alert">
                                                            <i class="fas fa-circle-info text-${bscolor}"></i>
                                                            <span> ${message}</span>
                                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                                    </div>`);
        setTimeout(function () {
            $(`${id} .alert`).alert('close');
        }, 3000);
    };
    $(document).ready(function () {
        if ("@ViewBag.InfoMsg" != "") alert("@Html.Raw(ViewBag.InfoMsg)", "info");
        if ("@ViewBag.WarnMsg" != "") alert("@Html.Raw(ViewBag.WarnMsg)", "warning");
        if ("@ViewBag.ErrMsg" != "") alert("@Html.Raw(ViewBag.ErrMsg)", "danger");

    })
</script>

BATCH336A/BATCH336A/Views/Shared/Partial/_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <button type="button" id="sidebarCollapse" class="btn btn-primary">
            <i class="fa fa-bars"></i>
            <span class="sr-only">Toggle Menu</span>
        </button>
        <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fa fa-bars"></i>
        </button>
        <form>
            <div class="input-group ms-3">
                <input type="text" class="form-control" placeholder="Cari sesuatu.." aria-label="Recipient's username" aria-describedby="button-addon2">
                <button class="btn btn-outline-primary" type="button" id="button-addon2"><i class="fa-solid fa-magnifying-glass"></i></button>
            </div>
        </form>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    <li class="me-2">
                        <div class="mt-1">
                            @(Context.Session.GetString("userFullname") != null ? "Halo, "+ Context.Session.GetString("userFullname") : "")
                        </div>
                    </li>
                    <li class="nav-item @(Context.Session.GetInt32("userId") != null ? "":"d-none")">
                        <div class="dropdown">
                            <button class="btn btn-outline-primary dropdown-toggle pe-3" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-gear"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
                                <li><a class="dropdown-item" href="#"><i class="fas fa-user"></i> Profile</a></li>
                                <li><a class="dropdown-item" asp-controller="Auth" asp-action="Logout"><i class="fas fa-door-open"></i> Logout</a></li>
                                <li><a class="dropdown-item" href="#"><i class="fas fa-gear"></i> Settings</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item  @(Context.Session.GetInt32("userId") != null ? "d-none":"")">
                        <button class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#modalPendaftaran1">Daftar</button>
                    </li>
                    <li class="nav-item  @(Context.Session.GetInt32("userId") != null ? "d-none":"")">
                        <button class="btn btn-primary ms-2" data-bs-toggle="modal" data-bs-target="#modalLogin">Masuk</button>
                    </li>
                </ul>
            </div>
        </div>
</nav>

BATCH336A/BATCH336A/Views/Shared/Partial/_ModalLogin.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="modal fade" id="modalLogin" data-bs-backdrop="static" data-bs-keyboard="false" aria-labelledby="exampleModalToggleLabel">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content mx-3">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="modalLoginLabel">Masuk</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body mx-4">
                <div class="h5">Selamat Datang Kembali</div>
                <div class="mb-3">Masukkan email dan password anda untuk masuk</div>
                <form id="formLogin">
                    <div>
                        <div class="mb-3">
                            <label>Email</label>
                            <input required type="email" name="Email" class="form-control form_login" placeholder="Masukkan email disini">
                            <div id="placeholderEmail"></div>
                        </div>
                        <div class="mb-3">
                            <label>Password</label>
                            <input required id="password" type="password" name="Password" class="form-control form_login" placeholder="masukkan password disini.." aria-describedby="passBtn">
                            <div id="placeholderPassword"></div>
                        </div>
                        <div class="input-group mb-3">
                            @* <button class="btn mb-3" onclick="togglePassword()" type="button" id="passBtn"></button> *@
                        </div>
                        <div id="placeholderLogin"></div>
                        <div><ul id="errorCheckLogin"></ul></div>
                        <div id="alertCekLogin"></div>
                        <center>
                            <button id="btnSubmitLogin" type="submit" class="btn btn-outline-primary w-100">MASUK</button>
                            <button class="btn btn-outline-primary d-none w-100" id="btnLoadingLogin" type="button" disabled>
                                <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                Loading...
                            </button>
                        </center>
                        <br />
                        <div class="text-center">
                            <div>
                                <a asp-action="Index" asp-controller="Auth">Lupa Password ?</a>
                            </div>
                            <div>
                                <span>atau</span>
                            </div>
                            <span>Belum memiliki akun?</span><a id="btnModalDaftar" data-bs-toggle="modal" data-bs-target="#modalPendaftaran1" class="text-decoration-none text-primary"> daftar</a>
                        </div>
                    </div>
                </form>
                <div><ul id="errorContainerLogin"></ul></div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $("#btnModalDaftar").click(function (e) {
            $("#modalLogin").modal("hide");
        })
    })
    $("#formLogin").validate({
        errorClass: "text-danger my-auto",
        // errorLabelContainer: "#errorCheckLogin",
        // wrapper: "li",
        rules: {
            Email: {
                "required": true,
                email:true
            },
            Password: {
                "required": true
            }
        },
        messages: {
            Email: {
                email : "masukkan alamat yang valid",
                "required": "Email harus terisi!"
            },
            Password: {
                "required": "Password harus terisi!"
            }
        },
        errorPlacement: function (error, element) {
            error.insertAfter(element);
        }
    });

    $("#btnSubmitLogin").click(function (e) {
        e.preventDefault();
        if ($("#formLogin").valid()) {
            $("#btnSubmitLogin").addClass("d-none");
            $("#btnLoadingLogin").removeClass("d-none");
            $.ajax({
                url: "/Auth/Login",
                type: "post",
                dataType: "json",
                data: $("#formLogin").serialize(),
                beforeSend: () => { },
                success: function (response) {
                    if (response.statusCode == 200) {
                        $("#modalLogin").modal("hide");
                        $("#btnLoadingLogin").addClass("d-none");
                        $("#btnSubmitLogin").removeClass("d-none");
                        setTimeout(() => {
                            location.reload();
                        },2000)
                        alert('Login Berhasil, Selamat datang!', 'success', "#placeholderHome");
                    }
                    else if (response.statusCode == 204) {
                        $("#btnLoadingLogin").addClass("d-none");
                        $("#btnSubmitLogin").removeClass("d-none");
                        alert('Password anda salah!', 'danger',"#placeholderPassword");
                    }
                    else if (response.statusCode == 403) {
                        $("#btnLoadingLogin").addClass("d-none");
                        $("#btnSubmitLogin").removeClass("d-none");
                        alert('Akun anda terblokir, silahkan buat akun baru!', 'danger', "#placeholderLogin");
                    }
                    else {
                        $("#btnLoadingLogin").addClass("d-none");
                        $("#btnSubmitLogin").removeClass("d-none");
                        alert('Email anda salah!', 'danger', "#placeholderEmail");
                    }
                },
                error: function (errResponse) {
                    
                }
            })

        }
    });

    $("#passBtn").addClass("fas fa-eye");

    function togglePassword() {
        let passwordInput = $("#password");

        if (passwordInput.attr("type") == "password") {
            passwordInput.attr("type", "text");
            $("#passBtn").addClass("fa-solid fa-eye-slash");
            $("#passBtn").removeClass("fas fa-eye");
        }
        else {
            passwordInput.attr("type", "password");
            $("#passBtn").removeClass("fa-solid fa-eye-slash");
            $("#passBtn").addClass("fas fa-eye");
        }
    }

</script>
    

BATCH336A/BATCH336A/Views/Shared/Partial/_ModalMedic.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!--Modal static-->
<div class="modal fade" id="staticModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="staticModalBody">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</div>
<!--Modal large-->
<div class="modal fade" id="staticModalLg" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticModalLabelLg">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body" id="staticModalBodyLg">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</div>

BATCH336A/BATCH336A/Views/Shared/Partial/_ModalSpec.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="modal fade" id="staticModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary" id="staticModalLabel">Modal title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="staticModalBody">
                <div class="spinner-grow" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
            </div>
        </div>
    </div>
</div>

BATCH336A/BATCH336A/Views/Shared/Partial/_SideProfile.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="d-flex flex-column gap-3">
        <div class="card border-0">
            <div class="card-body d-flex flex-column align-items-center">
                <div class="w-75 d-flex justify-content-end">
                    <div id="btn-update-photo" type="button" data-id="" data-bs-toggle="modal" data-bs-target="#staticModalE" class="px-2 py-1 bg-success rounded-circle text-white z-index-1 position-absolute ">
                        <i class="fa-solid fa-pen"></i>
                    </div>
                </div>
                <img class="img-profile mb-3 object-fit-cover rounded-circle" src="~/images/assets/empty.jpg" width="180" height="180">
                <div class="h1"><i class="fa-solid fa-star"></i></div>
                <p class="m-0">Bronze Member</p>
                <p class="fst-italic">Since </p>
            </div>
        </div>
        <div class="card border-0">
            
            <div class="card-body">
                <div class="mb-3">
                    <a class="h5 fw-bold text-black">Pasien</a>
                </div>
                <div class="mb-3">
                    <a class="h5 fw-bold text-black">Pembelian Obat</a>
                </div>
                <div class="mb-3">
                    <a class="h5 fw-bold text-black" asp-controller="HistoryAppointmentCustomer" asp-action="History">Riwayat Kedatangan</a>
                </div>
            </div>
        </div>
    </div>

BATCH336A/BATCH336A/Views/Shared/Partial/_Sidebar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    int? roleId = Context.Session.GetInt32("userRoleId");
    if (roleId == null)
    {
        roleId = null;
    }
}
<nav id="sidebar" class="active">
    <h1><a asp-controller="Home" asp-action="Index" class="logo"><span class="fas fa-stethoscope"></span> <span id="appName" style="font-size:20px;">Med.Id 336</span></a></h1>
    <ul class="list-unstyled components mb-5">
        <li>
            <a href="/Home" title="Beranda"><i class="fas fa-house"></i> <span id="tittle"> Beranda</span></a>
        </li>
        @if (ViewBag.Menu != null)
        {
            foreach (VMMMenu menu in ViewBag.Menu)
            {
                if (menu.Roles.Any(r => r.RoleId == roleId) || menu.Roles.Any(r => r.RoleId == 5))
                {
                    if(menu.SmallIcon != null)
                    {
                        @* <li class="active">
                            <a href="@menu.Url" title="@menu.Name">@Html.Raw(menu.SmallIcon) <span id="tittle">@menu.Name</span></a>
                        </li> *@
                        if (menu.ParentId == null || menu.ParentId == 0)
                        {
                            <li class="active">
                                <a href="#pageSubmenu-@menu.Id" data-toggle="collapse" aria-expanded="false" id="btnMenuDropdown" class="dropdown-toggle">@Html.Raw(menu.SmallIcon) <span id="tittle">@menu.Name</span></a>
                                    <ul class="collapse list-unstyled" id="pageSubmenu-@menu.Id">
                                        @foreach (VMMMenu submenu in ViewBag.Menu)
                                        {
                                            if (submenu.ParentId != null && submenu.ParentId == menu.Id)
                                            {
                                            <li><a href="@submenu.Url" style="color:yellow;" title="@menu.Name">@Html.Raw(submenu.SmallIcon) <span id="tittle">@submenu.Name</span></a></li>
                                            }
                                        }
                                    </ul>
                            </li>
                        }
                    }
                }
            }
        }

</nav>