BATCH336A/BATCH336A/Controllers/EducationLevelController.cs
using BATCH336A.Models;
using BATCH336A.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace BATCH336A.Controllers
{
    public class EducationLevelController : Controller
    {
        private readonly EducationLevelModel edulevel;
        private readonly MenuModel? menuModel;
        private readonly RoleModel role;
        private VMResponse response = new VMResponse();
        public EducationLevelController(IConfiguration _config, IWebHostEnvironment _webhost)
        {
            edulevel = new EducationLevelModel(_config);
            menuModel = new MenuModel(_config, _webhost);
            role = new RoleModel(_config);
        }
        public IActionResult Index(string? filter)
        {
            List<VMEducationLevel>? dataCategory = (filter == null) ? edulevel.GetAll() : edulevel.Search(filter);
            ViewBag.Title = "Education Level";
            ViewBag.Filter = filter;
            ViewBag.Role = role.GetAll();
            ViewBag.Menu = menuModel.GetAll();
            return View(dataCategory);
        }
        public IActionResult Add()
        {
            ViewBag.Title = "Education Level";
            ViewBag.Role = role.GetAll();
            ViewBag.Menu = menuModel.GetAll();

            return View();
        }
        [HttpPost]
        public async Task<VMResponse> Add(VMEducationLevel data)
        {
            if (!ModelState.IsValid)
            {
                response.statusCode = System.Net.HttpStatusCode.BadRequest;
                response.data = null;
                response.message = "Request tidak valid";
                return response;
            }
            response = await edulevel.CreateAsync(data);
            return response;
        }

        public IActionResult Edit(int id)
        {
            VMEducationLevel? categoryEditById = edulevel.GetById(id);
            ViewBag.Filter = id;
            ViewBag.Title = "Edit Education Level";
            ViewBag.Role = role.GetAll();
            ViewBag.Menu = menuModel.GetAll();

            return View(categoryEditById);
        }
        [HttpPost]
        public async Task<VMResponse> Edit(VMEducationLevel data)
        {
            if (!ModelState.IsValid)
            {
                response.statusCode = System.Net.HttpStatusCode.BadRequest;
                response.data = null;
                response.message = "Request tidak valid";
                return response;
            }
            response = await edulevel.UpdateAsync(data);
            return response;
        }

        public IActionResult Delete(int id)
        {
            ViewBag.Title = "Delete Category";
            ViewBag.EduName = edulevel.GetById(id).Name;
            ViewBag.Role = role.GetAll();
            ViewBag.Menu = menuModel.GetAll();

            return View(id);
        }

        [HttpPost]
        public async Task<VMResponse> Delete(int id, int userId)
        {
            response = await edulevel.DeleteAsync(id, userId);
            return response;
        }
    }
}

BATCH336A/BATCH336A/Views/EducationLevel/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
<div class="card">
    <div>
        <form id="frmEducationLevel" asp-controller="EducationLevel" asp-action="Add">
            <div class="mb-3">
                <label class="form-label">Education Level Name<span class="text-danger">*</span></label>
                <input type="text" class="form-control" name="Name" 
                placeholder="Input Education Level Name">
            </div>
            <div id="errorContainer" class="text-danger" aria-hidden="true"><ul></ul></div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
            <input type="hidden" name="CreatedBy" value="1"/>
        </form>
    </div>
</div>

<script>
        $("#staticModalLabel").html("@ViewBag.Title");

        $.validator.addMethod(
            "validationName",
            function (val,el){
            //check name with regex
            debugger
            return !(/^(?=.*[@@#$%^&*\-()_+=\/.,])/.test(val))
            },
            function(chckRes, el){
                let pass= $(el).val();
                let txtAlert = "Request Salah!";
                debugger
                if((/^(?=.*[@@#$%^&*\-()_+=\/.,])/.test(pass))){
                    txtAlert += "Tidak boleh karakter <br>"
                    console.log(txtAlert)
                }
                if (txtAlert == "Request Salah!"){
                    return txtAlert;
                }
                else{
                    return txtAlert
                }
            }
        )

        $("#frmEducationLevel").validate({
            errorClass: "text-danger",
            errorLabelContainer: "#errorContainer",
            wrapper: "li",
            rules: {
                Name :{
                    "required": true,
                    "minlength": 1,
                    "validationName":true
                }
            },
            messages: {
                Name: {
                    "required": "Harus Diisi",
                    "minlength": "Harus lebih dari 1 karakter",
                }
            }
        })

        $("#frmEducationLevel").submit(function(event){
            event.preventDefault();
            $("#errorContainer ul").empty()
            if ($("#frmEducationLevel").valid()){

                $.ajax({
                    url: '/EducationLevel/Add',
                    type: 'post',
                    data: $("#frmEducationLevel").serialize(),
                    dataType: 'json',
                    beforeSend: function(){
                        //process before send data
                    },
                    success: function(response){
                        debugger;
                        if (response.statusCode == 200 || response.statusCode == 201){
                        console.log(response);
                            location.reload();
                        }
                        else {
                            debugger;
                            $("#errorContainer ul").html("<li>" + response.message + "</li>");
                            $("#errorContainer").show();

                            //alert(response.message);
                        }
                    },
                    error: function(errResponse){
                        console.log("Gagal error")
                        debugger;
                    }
                });
            }
        });
</script>

BATCH336A/BATCH336A/Views/EducationLevel/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model int
@{
    Layout = null;
}
<div class="card">
    <div class="h3 card-header">

    </div>
    <div class="card-body">
        <i class="fas fa-exclamation-triangle float-xxl-start text-danger"></i>
        <span>Are you sure delete product with Name : @ViewBag.EduName.ToUpper() </span>
    </div>
    <div class="card-footer">
        <button id="btnDelete" class=" btn btn-danger">Confirm</button>
        <button class=" btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
    </div>
</div>



<script>
    $("#staticModalLabel").html("@ViewBag.Title");

    $("#btnDelete").click(
        ()=> {
        //if(confirm("Apakah yakin menghapus ini?")) {
            $.ajax({
                url: '/EducationLevel/Delete',
                type: 'post',
                data: {"id" : @Model, "userId": 1},
                dataType: 'json',
                beforeSend: function() {},
                success: function(response) {
                    if (response.statusCode == 200 ){
                        location.reload();
                    }
                    else {
                        alert(response.message);
                    }
                },
                error: function(errResponse){
                    console.log(errResponse)
                    alert("Delete failed!");

                    debugger;
                }
            });
        //}
    }); 
</script>

BATCH336A/BATCH336A/Views/EducationLevel/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VMEducationLevel?
@{
    Layout = null;
}
<form id="frmEditEduLevel" asp-controller="EducationLevel" asp-action="Edit">
<div class="card">
    <div>
        <input type="hidden" name="ModifiedBy" value="1"/>
        <input type="hidden" name="Id" value="@Model.Id"/>
        <input id="hiddenName" type="hidden" value="@Model.Name"/>

      <div class="mb-3">
        <label for="exampleInputEmail1" class="form-label">Category Name</label>
        <input type="text" class="form-control" name="Name" 
        id="nameInput" placeholder="Input Education Level Name" value="@Model.Name">
      </div>
      <div id="errorContainer" class="text-danger" aria-hidden="true"><ul></ul></div>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
</div>
</form>
<script>
        $("#staticModalLabel").html("@ViewBag.Title");
        //$("#frmEditCategory").validate();

        $.validator.addMethod(
            "validationName",
            function (val,el){
            //check name with regex
            debugger
            return !(/^(?=.*[@@#$%^&*\-()_+=\/.,])/.test(val))
            },
            function(chckRes, el){
                let pass= $(el).val();
                let txtAlert = "Request Salah!";
                debugger
                if((/^(?=.*[@@#$%^&*\-()_+=\/.,])/.test(pass))){
                    txtAlert = "Tidak boleh mengandung karakter <br>"
                    console.log(txtAlert)
                }
                if (txtAlert == "Request Salah!"){
                    return false;
                }
                else{
                    return txtAlert
                }
            }
        )

        $("#frmEditEduLevel").validate({
            errorClass: "text-danger",
            errorLabelContainer: "#errorContainer",
            wrapper: "li",
            rules: {
                Name :{
                    "required": true,
                    "minlength": 1,
                    "validationName":true
                }
            },
            messages: {
                Name: {
                    "required": "Harus Diisi",
                    "minlength": "Harus lebih dari 1 karakter",
                }
            }
        })

        $("#frmEditEduLevel").submit(function(event){
            event.preventDefault();
            $("#errorContainer ul").empty()
            if($("#frmEditEduLevel").valid()){
                let oldName = $("#hiddenName").val()
                let newName = $("#nameInput").val()
                $.ajax({
                    url: '/EducationLevel/Edit',
                    type: 'post',
                    data: $("#frmEditEduLevel").serialize(),
                    dataType: 'json',
                    beforeSend: function(){
                    },
                    success: function(response){
                        console.log(response)
                        if(response.statusCode == 200 || response.statusCode == 201){
                            alert("Berhasil mengupdate data " + response.data.name ) 
                            location.reload();
                        }
                        else{
                            $("#errorContainer ul").html("<li>" + response.message + "</li>");
                            $("#errorContainer").show();
                            //alert(response.message);
                        }
                    },
                    error: function(errResponse){
                    }
                });
            }
        });
</script>

BATCH336A/BATCH336A/Views/EducationLevel/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model List<VMEducationLevel>?
@{
    int nomor = 1;
}
<partial name="Partial/_ModalMedic" />

<div class="card">
    <div class=" card-header h1 text-center">
      Education Level
    </div>
    <div class="card-body">
        <div class="d-flex justify-content-between" >
            <button class="btn btn-primary mb-3" title="Add.." data-bs-toggle="modal" data-bs-target="#staticModal"><i class="fa-solid fa-plus"></i></button>
            <form class="mb-3 w-50" id="frmFilter" asp-controller="EducationLevel" asp-action="Index">
                <div class="input-group">
                    <input name="filter" id="filter" type="text" class="form-control" placeholder="Search By Education Level" 
                    aria-label="Filter" aria-describedby="iSearch" value="@ViewBag.Filter"/>
                    <button type="submit" class="input-group-text" id="basic-addon2"><i class="fa-solid fa-magnifying-glass"></i></button>
                </div>
            </form>
        </div>
            <table class="table text-center table-striped table-hover">
                <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                @if (Model != null)
                {
                    @foreach (VMEducationLevel data in Model)
                    {
                        <tr class="text-center">
                            <td class="col-1">@nomor</td>
                            <td class="col-8">@data.Name.ToUpper()</td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-success" title="Edit.." data-id="@data.Id" data-bs-toggle="modal" data-bs-target="#staticModal"><i class="fa-solid fa-pen-to-square"></i></button>
                                    <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#staticModal" data-id="@data.Id" title="Delete.."><i class="fa-solid fa-trash"></i></button>
                                </div>
                            </td>
                        </tr>
                        nomor++;
                    }
                }
                else
                {
                    <tr > 
                        <marquee direction="right">
                                <td colspan ="3" class="text-center">Tidak ada data</td>
                        </marquee>
                    </tr>    
                }
                </tbody>
            </table>
    </div>
</div>
<script>

    $(".btn-primary").click(function(event){
    $("#staticModalBody").load("/EducationLevel/Add");
    })
    $(".btn-success").click(function(event){
        let catId = $(this).data("id");
    $("#staticModalBody").load("/EducationLevel/Edit/"+catId)
    })
    $(".btn-danger").click(function(event){
        let catId = $(this).data("id");
    $("#staticModalBody").load("/EducationLevel/Delete/"+catId)
    })
</script>