BATCH336A/BATCH336A/Controllers/DetailDokterController.cs
using BATCH336A.Models;
using BATCH336A.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace BATCH336A.Controllers
{
    public class DetailDokterController : Controller
    {
        private readonly DetailDokterModel detaildokter;
        private readonly MenuModel? menuModel;
        private readonly RoleModel role;
        private VMResponse response = new VMResponse();

        public DetailDokterController(IConfiguration _config, IWebHostEnvironment _webhost) {
            detaildokter = new DetailDokterModel(_config);
            menuModel = new MenuModel(_config, _webhost);
        }

        public IActionResult Index() {
            ViewBag.Role = role.GetAll();
            ViewBag.Menu = menuModel.GetAll();
            return View();
        }

        public IActionResult Details(long _id)
        {
            ViewBag.Profile = detaildokter.GetProfile(_id);
            ViewBag.Education = detaildokter.GetEducation(_id);
            ViewBag.Medis = detaildokter.GetMedis(_id);
            ViewBag.Riwayat = detaildokter.GetRiwayat(_id);
            ViewBag.Jadwal = detaildokter.GetJadwal(_id);
            ViewBag.Lokasi = detaildokter.GetLokasi(_id);
            ViewBag.Role = role.GetAll();
            ViewBag.Menu = menuModel.GetAll();
            return View();
        }
    }
}

BATCH336A/BATCH336A/Views/DetailDokter/Details.cshtml
@using System.Globalization;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    int tombol = 0;
    string hari = "";
    List<VMDetailDokter>? jadwal = ViewBag.Jadwal;
}
<div class="container">
    <div class="row">
        <div class="col-4">
            <div style="marginTop: 100px"></div>

            <div class="row">
              <div class="col-10 mx-auto">
                <div >
                  <div class="card-body profile-card d-flex flex-column"  >
                      <img class="rounded-circle" style="height:166px; width:166px" src="~/images/@ViewBag.Profile.Image"/>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h5>
                <b>Tindakan Medis</b>
              </h5>
            </div>

            <div>
              <div class="row">
                <div class="col-xl-10">
                  <div class="card">
                    <div class="card-body profile-card d-flex flex-column ">
                        @foreach(VMDetailDokter? TindakanMedis in ViewBag.Medis)
                        {
                           <ul class="mb-1 mr-1" style="list-style-type: circle;color:black">
                               <li>@TindakanMedis.TreatmentName</li>
                           </ul>    
                        }
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h1> </h1>
              <h5>
                <b>Riwayat Praktek</b>
              </h5>
            </div>

            <div class="row">
              <div class="col-xl-10">
                <div class="card">
                  <div class="card-body profile-card d-flex flex-column ">
                    @foreach(VMDetailDokter RiwayatPraktek in ViewBag.Riwayat)
                    {
                        <h6 style="color:black">@RiwayatPraktek.FacilityName</h6>
                        <div class="row ">
                            <div class="col d-flex ">
                                    <p style="font-size:10px;color:black">
                                    @RiwayatPraktek.Specialization
                                </p>
                                <p >
                                @if (RiwayatPraktek.EndIsYear == null)
                                {
                                        <p style="margin-left: auto; font-size: 10px;color:black">@(RiwayatPraktek.StartYear?.ToString("yyyy")) - sekarang</p>
                                }
                                else
                                {
                                        <p style="margin-left: auto; font-size: 10px;color:black">@(RiwayatPraktek.StartYear?.ToString("yyyy")) - @(RiwayatPraktek.EndIsYear?.ToString("yyyy"))</p>
                                }
                                </p>
                            </div>
                        </div>
                    }
                  </div>
                </div>
              </div>
            </div>

            <div>
              <h1> </h1>
              <h5>
                <b>Riwayat Pendidikan</b>
              </h5>
            </div>

            <div class="row">
              <div class="col-xl-10">
                <div class="card">
                  <div class="card-body profile-card d-flex flex-column ">
                    @foreach(VMDetailDokter Education in ViewBag.Education)
                    {
                        <h6 style="color:black">@Education.InstitutionName</h6>
                        <div class="row">
                            <div class="col d-flex">
                                <p style=" font-size: 10px;color:black">
                                    @Education.Major 
                                </p>
                                <p style="margin-left: auto; font-size: 10px;color:black">
                                    @Education.EndYear
                                </p>
                            </div>
                        </div>
                    }
                  </div>
                </div>
              </div>
            </div>

        </div>
        
        <div class="col-8">
            <div class="row mt-5 mb-5">
                <div class="col-xl-9">
                    <div class="card-body profile-card ">
                        <h6 class="mb-1" style=" font-size: 20px;color:black">
                            <b>@ViewBag.Profile.DoctorName</b>
                        </h6>
                        <h6 class="mb-1 ms-3"style=" font-size: 15px;color:black" >
                            @ViewBag.Profile.DoctorSpecialization
                        </h6>
                        <h6 class="mb-1 ms-3" style=" font-size: 15px;color:black">
                            @ViewBag.Profile.Pengalaman tahun pengalaman
                        </h6>
                    </div>
                </div>
                <div class="col-xl-3 mt-4 ">
                    @foreach(VMDetailDokter Jam in ViewBag.Jadwal)
                    {
                        hari = DateTime.Now.ToString("dddd",new CultureInfo("id-ID"));
                        @if (hari == Jam.Day && (TimeSpan.Parse(DateTime.Now.ToString("HH:mm:ss")) >= TimeSpan.Parse(Jam.StartJam+":00")
                        && TimeSpan.Parse(DateTime.Now.ToString("HH:mm")) <= TimeSpan.Parse(Jam.EndJam)))
                        {
                            tombol++;
                        }
                    }
                    @if (tombol >= 1)
                    {
                        <button class="btn btn-primary">Chat dokter</button>
                        <h6 class="ms-4" style="color:black;font-size:14px">Rp. 80.000</h6>
                    }
                    else
                    {
                        <button class="btn btn-primary" disabled>Chat dokter</button>
                    }
                </div>
            </div>
            <div class="row mt-5">
                <div>
                    <h5>
                        <b>Lokasi Praktek</b>
                    </h5>
                </div>
                @foreach(VMDetailDokter Lokasi in ViewBag.Lokasi)
                {
                    <div class="accordion mb-5" id="accordionExample">
                        <div class="accordion-item">
                        <div class="card">
                            <div class="row">
                                <div class="col-xl-9">
                                    <h6 class="mb-1 mt-3 ms-3"  style="color:black">
                                        @Lokasi.NameMF
                                    </h6>   
                                    <h6 class="mb-1 ms-4" style="color:black;font-size:12px">@Lokasi.Specialization</h6>
                                    <h6 class="mb-3 ms-4" style="color:black;font-size:12px"><i class="fa-solid fa-map-pin"></i> @Lokasi.LocationName</h6>
                                </div>
                                <div class="col-xl-3 mt-4" style="color:black;font-size:12px">
                                    <p class="mb-0">
                                            Konsultasi dimulai dari
                                    </p>
                                    <p class="mb-0 mt-0 ms-4">
                                        Rp. @string.Format("{0:N0}",Lokasi.Price),00
                                    </p>
                                </div>
                            </div>
                        </div>
                        
                        <h2 class="accordion-header" id="headingOne" data-id="@Lokasi.IdMf">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@Lokasi.IdMf" aria-expanded="false" aria-controls="collapseOne">
                                    <h6 class="mt-0 mb-0" style="color:black;font-size:12px"><span id="txtChange-@Lokasi.IdMf">Tampilkan</span> Jadwal Dokter</h6>     
                            </button>
                        </h2>
                        <div id="collapse-@Lokasi.IdMf" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <div class="row">
                                    <div class="col-1">
                                        @foreach(VMDetailDokter Jadwal in jadwal.Where(j => j.IdMf == Lokasi.IdMf))
                                        {   
                                            <p style="color:black">
                                                @Jadwal.Day 
                                            </p>
                                        }
                                    </div>
                                    <div class="col-8">
                                        @foreach (VMDetailDokter Jadwal in jadwal.Where(j => j.IdMf == Lokasi.IdMf))
                                        {   
                                            <p style="color:black">
                                             @Jadwal.Schedule
                                            </p>
                                        }
                                    </div>
                                    <div class="col-3">
                                        <button class="btn btn-primary mt-3">Buat Janji</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>   
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<script>
    
    $(".accordion-header").click(function(e){
        let id = $(this).data("id");
        if($("#txtChange-"+id).text()=="Tampilkan"){
            $("#txtChange-"+id).text("Sembunyikan");
        }
        else{
            $("#txtChange-"+id).text("Tampilkan");
        }
    });
</script>

BATCH336A/BATCH336A/Views/DetailDokter/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="row">
    <div class="col-4"></div>
    <div class="card col-4 mt-5">
        <form id="frmIdDetail" asp-controller="DetailDokter" asp-action="Details" method="post">
            <div class="mb-3">
                <label style="font-size: 25px;color:black"  class="form-label">Id Dokter<span class="text-danger">*</span></label>
                <input style="font-size: 15px;color:black" type="number" class="form-control width: 20px" name="_id"
                id="idInput" placeholder="Input Id Dokter">
            </div>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <button type="submit" class="btn btn-primary " style="font-size: 15px">Submit</button>
            </div>
        </form>
    </div>
    <div class="col-4"></div>
</div>