BATCH336A/BATCH336A/Controllers/CourierController.cs
using Microsoft.AspNetCore.Mvc;
using BATCH336A.Models;
using BATCH336A.ViewModel;
using System.Diagnostics;
using System;
using System.Drawing.Printing;
using BATCH336A.AddOns;
using Microsoft.EntityFrameworkCore;



namespace BATCH336A.Controllers
{
    public class CourierController : Controller
    {
        private VMResponse response = new VMResponse();
        private readonly CourierModel courier;
        private readonly int pageSize;
        private readonly MenuModel? menuModel;
        private readonly RoleModel role;
        public CourierController(IConfiguration _config, IWebHostEnvironment _webHostEnv)
        {
            courier = new CourierModel(_config);
            pageSize = int.Parse(_config["PageSize"]);
            menuModel = new MenuModel(_config, _webHostEnv);
            role = new RoleModel(_config);
        }

        //public IActionResult Index(string? filter)
        //{
        //    List<VMMCourier>? data = new List<VMMCourier>();
        //    if (filter == null)
        //    {
        //        data = courier.GetAll();
        //    }
        //    else
        //    {
        //        data = courier.GetBy(filter);
        //    }
        //    ViewBag.Title = "Courier Index";
        //    ViewBag.Filter = filter;
        //    return View(data);
        //}

        public IActionResult Index(string? filter, string? orderBy, int? pageNumber, int? currPageSize)
        {
            List<VMMCourier>? data = new List<VMMCourier>();
            if (filter == null)
            {
                data = courier.GetAll();
            }
            else
            {
                data = courier.GetBy(filter);
            }

            ViewBag.PageSize = (currPageSize ?? pageSize);
            ViewBag.Title = "Courier Index";
            ViewBag.Filter = filter;
            ViewBag.Role = role.GetAll();
            ViewBag.Menu = menuModel.GetAll();

            return View(Pagination<VMMCourier>.Create(data, pageNumber ?? 1, ViewBag.PageSize));
        }

        public IActionResult Add()
        {
            ViewBag.Title = "Create New Courier";
            return View();
        }

        [HttpPost]
        public async Task<VMResponse> Add(VMMCourier data)
        {
            response = await courier.CreateAsync(data);
            return response;
        }
        public IActionResult Edit(int id)
        {
            VMMCourier? data = courier.GetById(id);
            ViewBag.Title = "Edit Courier";
            return View(data);
        }

        [HttpPost]
        public async Task<VMResponse> Edit(VMMCourier data)
        {
            response = await courier.UpdateAsync(data);
            return response;
        }
        public IActionResult Delete(long id)
        {
            VMMCourier data = courier.GetById(id);
            ViewBag.Title = "Delete Confirmation";
           
            return View(data);
        }

        [HttpPost]
        public async Task<VMResponse> Delete(int id, int DeletedBy)
        {
            response = await courier.DeleteAsync(id, DeletedBy);
            return response;
        }
        
    }
}

BATCH336A/BATCH336A/Views/Courier/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}

<form id="frmCourier" asp-action="Add" asp-controller="Courier">
    <div class="card">
        <div class="card-body">
            <div class="input-group mb-3">
                <label class="input-group-text col-3">Nama<span class="text-danger">*</span></label>
                <input required name="Name" type="text" class="form-control" placeholder="Input Courier Name..." aria-label="CourierName" aria-describedby="basic-addon1">
               
            </div>
      
            <div class="input-group mb-3">
                <input name="CreatedBy" type="hidden" value="1" class="form-control" placeholder="Input Courier Description..." aria-label="Description" aria-describedby="basic-addon1">
            </div>
            <div> <ul id="errorContainer"></ul> </div>
        </div>
        <div class="card-footer d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="Submit">
        </div>
    </div>
</form>

<script>
    // Add a custom method to disallow strings consisting only of spaces
    $.validator.addMethod("noSpacesOnly", function (value, element) {
        return /\S/.test(value);
    }, "Cannot be all spaces");



    $("#frmCourier").validate({
        errorClass: "text-danger",
        errorLabelContainer: "#errorContainer",
        wrapper: "li",
        rules: {
            Name: {
                minlength: 2,
                maxlength: 100,
                required: true,
                noSpacesOnly: true
            }
        },
        messages: {
            Name: {
                required: "Masukan Nama Courier!",
                minlength: "Minimum length is 2 characters",
                maxlength: "Maximum length is 100 characters"
            }
        }
    });

    $("#frmCourier").submit(function (event) {
        // Disable submit default
        event.preventDefault();

        if ($("#frmCourier").valid()) {

            $.ajax({
                url: '/Courier/Add',
                type: 'post',
                data: $("#frmCourier").serialize(),
                dataType: 'json',
                beforeSend: function () {
                    // You can add any loading indicators or actions here
                },
                success: function (response) {
                    debugger;
                    if (response.statusCode == 200 || response.statusCode == 201) {
                        location.reload();
                    } else {
                        alert(response.message);
                    }
                },
                error: function (errResponse) {
                    debugger;
                }
            });
        }
    });

   </script>

BATCH336A/BATCH336A/Views/Courier/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VMMCourier
@{
    Layout = null;
}

<div class="card">
    <div class="card-body">
        <i class="fas fa-exclamation-triangle float-xxl-start text-danger"></i>
        <span>Are you sure you want to delete Courier with Name = @Model.Name?</span>
    </div>
    <div class="card-footer">
        <button class="btn btn-danger" id="btnDeleteCourier">Confirm</button>
        <button class="btn btn-secondary" data-bs-dismiss="modal" aria-label="Close">Cancel</button>
    </div>
</div>

<script>
    $("#staticModalLabel").html("@ViewBag.Title");

    $("#btnDeleteCourier").click(() => {
        $.ajax({
            url: '/Courier/Delete',
            type: 'post',
            data: { "id": @Model.Id, "DeletedBy": 3 },
            dataType: 'json',
            beforeSend: function () { },
            success: function (response) {
                if (response.statusCode == 200) {
                    location.reload();
                }
                else {
                    alert(response.message);
                }
            },
            error: function (errResponse) {
                alert("Delete failed!");
                debugger;
            }
        });
    });
</script>

BATCH336A/BATCH336A/Views/Courier/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model VMMCourier?
@{
    Layout = null;
}

<form id="frmCourier" method="post" asp-action="Edit" asp-controller="Courier">
    <div class="card">
        <div class="card-body">
            <input type="hidden" name="Id" value="@Model.Id" />
            <input type="hidden" name="ModifiedBy" value="2" />
            <div class="input-group mb-3">
                <label class="input-group-text col-3">Name</label>
                <input name="Name" type="text" class="form-control" placeholder="Input Courier Name..." aria-label="CourierName" aria-describedby="basic-addon1" value="@Model.Name">
            </div>
      
        </div>
        <div class="card-footer d-flex justify-content-end">
            <input class="btn btn-primary" type="submit" value="Submit">
        </div>
    </div>
</form>

<script>
    $("#staticModalLabel").html("@ViewBag.Title");
    $.validator.addMethod("noSpacesOnly", function (value, element) {
        return /\S/.test(value);
    }, "Cannot be all spaces");

    $("#frmCourier").validate({
        errorClass: "text-danger",
        errorLabelContainer: "#errorContainer",
        wrapper: "li",
        rules: {
            Name: {
                minlength: 2,
                maxlength: 100,
                required: true,
                noSpacesOnly: true
            }
        },
        messages: {
            Name: {
                required: "Masukan Nama Courier!",
                minlength: "Minimum length is 2 characters",
                maxlength: "Maximum length is 100 characters"
            }
        },
        submitHandler: function () {
            return false;
        }
    });

    $("#frmCourier").submit(function (event) {
        //Disable submit default
        event.preventDefault();

        if ($("#frmCourier").valid()) {
            $.ajax({
                url: '/Courier/Edit',
                type: 'post',
                data: $("#frmCourier").serialize(),
                dataType: 'json',
                beforeSend: function () {

                },
                success: function (response) {
                    if (response.statusCode == 200 || response.statusCode == 201) {
                        location.reload();
                    }
                    else {
                        alert(response.message);
                    }
                },
                error: function (errResponse) {
                    debugger;
                }
            });
        }
    });
</script>

BATCH336A/BATCH336A/Views/Courier/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Pagination<VMMCourier>

@{
}

<div class="card">
    <div class="card-header h3" style="background-color: lightblue; color: navy; padding: 10px;">Courier Index</div>
    <div class="card-body">
        <div class="d-flex justify-content-between mb-3">
           
            <form class="w-50" id="frmFilter" asp-controller="Courier" asp-action="Index">
                <div class="input-group">
                    <input id="filter" name="filter" type="text" class="form-control" placeholder="Category Name or Description" aria-label="Filter" aria-describedby="iSearch" value="@ViewBag.Filter">
                    <button type="submit" class="btn btn-secondary input-group-text" id="iSearch"><i class="fa-solid fa-search"></i></button>
                </div>
            </form>
            <button class="btn btn-primary" title="Add" data-bs-toggle="modal" data-bs-target="#staticModal">Tambah</button>
        </div>
        <div class="card-header h3" style="background-color: lightblue; color: navy; padding: 5px;">nama</div>
        <div class="card-body">
            <div>
                <div>
                    <table class="w-100">
                        <thead>
                            <tr>
                                
                                <th>NAME</th>
                                <th class="text-center">ACTION</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                @foreach (VMMCourier data in Model)
                                {
                                    <tr>
                                        
                                        <td>@data.Name</td>
                                        <td class="col-2 text-center">
                                            <div class="btn-group">

                                                <button class="btn btn-warning" title="Edit" data-id="@data.Id" data-bs-toggle="modal" data-bs-target="#staticModal"><i class="fa-solid fa-pen-to-square"></i></button>
                                                <button class="btn btn-danger" title="Delete" data-id="@data.Id" data-name="@data.Name" data-bs-toggle="modal" data-bs-target="#staticModal"><i class="fa-solid fa-trash-can"></i></button>

                                            </div>
                                        </td>

                                    </tr>
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4" class="text-center">tidak ada data</td>
                                </tr>
                            }
                        </tbody>
                    </table>

                </div>

            </div>
        </div>
        <div class="card-footer d-flex justify-content-center">
            <div class="input-group w-25">
                <a class="btn btn-secondary col-2 @(Model.PageIndex <= 1 ? "disabled": "")" title="Previous Page"
                   asp-controller="Courier" asp-action="Index" asp-route-filter="@ViewBag.Filter"
                   asp-route-currPageSize="@ViewBag.PageSize"
                   asp-route-pageNumber="@(Model.PageIndex <= 1 ? Model.PageIndex : Model.PageIndex-1)"
                   asp-route-orderBy="@ViewBag.OrderBy"><i class="fas fa-chevron-left"></i></a>
                <div class="input-group-text text-center col-6"><span class="w-100">@Model.PageIndex of @Model.TotalPages</span></div>
                <a class="btn btn-secondary col-2 @(Model.PageIndex >= Model.TotalPages ? "disabled": "")" title="Next Page"
                   asp-controller="Courier" asp-action="Index" asp-filter="@ViewBag.Filter"
                   asp-route-currPageSize="@ViewBag.PageSize"
                   asp-route-pageNumber="@(Model.PageIndex >= Model.TotalPages ? Model.PageIndex : Model.PageIndex+1)"
                   asp-route-orderBy="@ViewBag.OrderBy"><i class="fas fa-chevron-right"></i></a>
            </div>
            <div class="input-group w-25">
                <label class="input-group-text" for="currPageSize">Page Size:</label>
                <select class="form-select" id="currPageSize">
                    @for (int i = 5; i <= 15; i += 5)
                    {
                        if (ViewBag.PageSize == i)
                        {
                            <option value="@i" selected>@i</option>
                        }
                        else
                        {
                            <option value="@i">@i</option>
                        }
                    }
                </select>
            </div>
        </div>
    </div>
    </div>
<script>
    $("#currPageSize").change(function (event) {
        location.replace("/Courier/Index?filter=@ViewBag.Filter&orderBy=@ViewBag.OrderBy&currPageSize=" + $(this).val())
    });
    $(".btn-primary").click(function (event) {
        $("#staticModalBody").load("/Courier/Add");
    });

    

    $(".btn-warning").click(function (event) {
        let catId = $(this).data("id");
        $("#staticModalBody").load("/Courier/Edit/" + catId);
    });

    $(".btn-danger").click(function (event) {
        let catId = $(this).data("id");
        $("#staticModalBody").load("/Courier/Delete/" + catId);
    });
</script>